---

name: Deploy vutils-testing

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the project
        uses: actions/checkout@v2

      - name: Setup Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build

      - name: Deploy package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          token: ${{ secrets.PYPI_API_TOKEN }}
